### ISSUE TITLE
Real space RAMLAK

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-filters#103]
Computing the filter directly in the fourier space is much more efficient but causes aliasing in the reconstruction as described [here](http://www.ncbi.nlm.nih.gov/pubmed/18222805). It would be nice to support the filter computation in the real space, for this we would need to transform the coefficients. From what I have seen in the [phase retrieval](https://github.com/ufo-kit/ufo-filters/blob/master/src/ufo-retrieve-phase-task.c) the FFT is handled directly in the filter. I was thinking that this probably isn't the last time we will need to do FFTs internally so maybe some convenience functions would come in handy. Another option is to implement a separate task and connect it to IFFT and then the rest of the reco pipeline but that means ifs and elses in scripts and further code which I don't like too much.

Since I am digging into this I would also like to add some mollification to the filtering (we could suppress the high-frequencies in the RAMLAK) and there one could have also choices from different mollifiers.

Last, we could even support arbitrary coefficients, like:
```python
fltr = pm.get_task('filter')
# New fancy coefficients
fltr.props.coeffs = np.ones(n, dtype=np.float32)
```
But then again, that's not so elegant to hook up with what's in tofu already. What do you think @matze?

An example shows a slice of a reconstructed cylinder filtered by computing the filter in real space and taking the FFT (red) vs. filtering with computed Fourier coefficients directly (blue).

![figure_3](https://cloud.githubusercontent.com/assets/2648829/11566896/bb3af676-99e4-11e5-881c-fa81fcfde846.png)

You see there is a global offset and the blue curve is somehow bent. The ground truth is set to be one, so the real filtering comes closer.

**Comment by matze** [comment]
I think, I'd go for the first option, i.e. wrapping the FFT code as good as possible in a (static) library and let that be used by `fft`, `ifft`, `phase-retrieve` and the adapted `filter` task. The upside is that we can also reduce redundant code which is even more troublesome since we support both AMD and Apple FFT.

> Last, we could even support arbitrary coefficients

Mind you, that you can only use GType- or GObject-based properties. In this case you'd need to pass a Python list or get down to the NumPy C-array. Simply passing a NumPy array object is not going to work. But in principle, why not?

**Comment by tfarago** [comment]
OK, that's what I like the best too. Could you provide that FFT infrastructure please? It's not urgent. I would then make the new filter and also implement the arbitrary coefficients.

**Comment by matze** [comment]
> Could you provide that FFT infrastructure please?

Yes, will do!

**Comment by matze** [comment]
I wasn't yet very successful with the leak hunt, so I was working on that to distract myself. A stupid round-trip test was successful but I have no idea about global implications of this change. But in any case, you might check this for the real space filtering.

**Comment by tfarago** [comment]
Thanks, I will check it out.
