### ISSUE TITLE
median filter - two problems

### ISSUE THREAD

**Issue by milkdrop** [ufo-kit/ufo-filters#118]
1) ufo-query -p medianfilter
Error: ufo_medianfilter_task_new is not exported by module libufofiltermedianfilter.so: `ufo_medianfilter_task_new': /usr/lib/ufo/libufofiltermedianfilter.so: undefined symbol: ufo_medianfilter_task_new

2) ufo-launch read path="ADU/CT2_Abs_*.tif" ! medianfilter ! write filename=ProjAbsMedF/CT2_Abs_Proj_%04i.tif
Error parsing pipeline: ufo_medianfilter_task_new is not exported by module libufofiltermedianfilter.so: `ufo_medianfilter_task_new': /usr/lib/ufo/libufofiltermedianfilter.so: undefined symbol: ufo_medianfilter_task_new

**Comment by matze** [comment]
The name of the filter is `median-filter`, i.e. `ufo-query -p median-filter` works. I know that `ufo-query -l` returns `medianfilter` however this is a problem for all tasks with several name components. As of now, this cannot be fixed other than maybe renaming the filter to `Median` or `Medianfilter`.
