### ISSUE TITLE
How to get GPU name in a task?

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-filters#120]
I optimized the back projection kernel in #119 but I forgot that to actually get the speedup I need to set the work group size myself. I guess the correct way is to implement `CL_DEVICE_NAME` inside `ufo_gpu_node_get_info`, right?

**Comment by tfarago** [comment]
@matze is assigned only to answer the question, not to actually implement it :wink:

**Comment by matze** [comment]
Yep, that would be reasonable. Even though this all works great for identifying NVIDIA GPU models, it fails flatly for AMD cards which have a pretty generic name like "Hawaii".

**Comment by tfarago** [comment]
Yeah those are very helpful :smile:
