### ISSUE TITLE
Please make oclfft optional

### ISSUE THREAD

**Issue by picca** [ufo-kit/ufo-filters#124]
Hello,

now that ufo-core was uploaded into Debian, I am preparing the filters part :).
I prefer to remove the oclfft code in oder to upload ufo-filters.
so I will repack by removing the oclfft directory.

this imply that the deps/CMakefileTxt should not fail when oclfft directory is missing.
could you add an option in order to compile with oclfft which should be ON or OFF as you convenience.

thanks

Fred

**Comment by picca** [comment]
Hello Matthias

Is it possible to put the option in the deps/CMakefileTxt instead of the oclfft one, and to include optionnaly the oclfft/ directory if the option is ON.

This way I can remove the oclfft directory with a simple
rm -rf deps/oclfft
No need to keep only the oclfft/CMakefileTxt

thanks

Fred

**Comment by matze** [comment]
Should be good now.
