### ISSUE TITLE
Debian warning during  build

### ISSUE THREAD

**Issue by picca** [ufo-kit/ufo-filters#126]
Hello, I will put here the warning obersev during the buildof ufo-filters

```
/home/picca/Debian/ufo-filters/ufo-filters/src/ufo-fftmult-task.c: In function ‘get_max_work_group_size’:
/home/picca/Debian/ufo-filters/ufo-filters/src/ufo-fftmult-task.c:108:23: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     *x_worker_count = ULLONG_MAX;
                       ^~~~~~~~~~
[ 78%] Linking C shared library libufofilterfftmult.so


/home/picca/Debian/ufo-filters/ufo-filters/src/ufo-lamino-backproject-task.c: In function ‘ufo_lamino_backproject_task_setup’:
/home/picca/Debian/ufo-filters/ufo-filters/src/ufo-lamino-backproject-task.c:202:27: warning: ‘kernel_filename’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     priv->scalar_kernel = ufo_resources_get_kernel (resources, kernel_filename, "backproject_burst_1", error);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
It seems that you forgot to link against m ;)

```
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterremovecircle.so contient une référence au symbole sqrtf qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterfilterstripes1d.so contient une référence au symbole exp qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofiltervolumerender.so contient une référence au symbole sincos qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofiltercutsinogram.so contient une référence au symbole roundf qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterfilter.so contient une référence au symbole cos qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: 12 autres avertissements semblables ont été sautés (utiliser -v pour les voir tous).
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofiltercontrast.so contient une référence au symbole sqrt qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: 2 autres avertissements semblables ont été sautés (utiliser -v pour les voir tous).
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterfilterparticle.so contient une référence au symbole round qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: 2 autres avertissements semblables ont été sautés (utiliser -v pour les voir tous).
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterblur.so contient une référence au symbole exp qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterzeropad.so contient une référence au symbole pow qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: 2 autres avertissements semblables ont été sautés (utiliser -v pour les voir tous).
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterdenoise.so contient une référence au symbole sqrtf qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterfftmult.so contient une référence au symbole sqrtf qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofiltermapslice.so contient une référence au symbole ceil qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: 1 autre avertissement semblable a été sauté (utiliser -v pour les voir tous)
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofiltergetdupcirc.so contient une référence au symbole sqrtf qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterdumpring.so contient une référence au symbole roundf qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: 2 autres avertissements semblables ont été sautés (utiliser -v pour les voir tous).
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterlaminobackproject.so contient une référence au symbole ceil qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: 6 autres avertissements semblables ont été sautés (utiliser -v pour les voir tous).
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterpolarcoordinates.so contient une référence au symbole sqrt qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: 2 autres avertissements semblables ont été sautés (utiliser -v pour les voir tous).
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterbackproject.so contient une référence au symbole sin qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: 1 autre avertissement semblable a été sauté (utiliser -v pour les voir tous)
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterdfisinc.so contient une référence au symbole cos qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: 2 autres avertissements semblables ont été sautés (utiliser -v pour les voir tous).
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterringpattern.so contient une référence au symbole sqrt qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterringwriter.so contient une référence au symbole roundf qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
```

**Comment by matze** [comment]
Can you check if the latest three commits fix these problems?

**Comment by picca** [comment]
I found a few more with the full buildlog

-- Configuring done
CMake Warning (dev) at docs/CMakeLists.txt:27 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "ufo" of target "manual" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by picca** [comment]
reading sources... [100%] sinks

../../NEWS:44: WARNING: Inline interpreted text or phrase reference start-string without end-string.
looking for now-outdated files... none found

**Comment by picca** [comment]
/home/picca/Debian/ufo-filters/ufo-filters/src/ufo-transpose-task.c: In function ‘ufo_transpose_task_process’:
/home/picca/Debian/ufo-filters/ufo-filters/src/ufo-transpose-task.c:108:10: warning: unused variable ‘fast_height’ [-Wunused-variable]
     gint fast_height = height - height % 4;
          ^~~~~~~~~~~
/home/picca/Debian/ufo-filters/ufo-filters/src/ufo-transpose-task.c:107:10: warning: unused variable ‘fast_width’ [-Wunused-variable]
     gint fast_width = width - width % 4;
          ^~~~~~~~~~
[ 11%] Linking C shared library libufofiltertranspose.so

**Comment by picca** [comment]
/home/picca/Debian/ufo-filters/ufo-filters/src/readers/ufo-edf-reader.c: In function ‘ufo_edf_reader_read’:
/home/picca/Debian/ufo-filters/ufo-filters/src/readers/ufo-edf-reader.c:124:23: warning: self-comparison always evaluates to false [-Wtautological-compare]
         if (num_bytes != num_bytes)
                       ^~
[ 25%] Building C object src/CMakeFiles/ufofilterread.dir/readers/ufo-raw-reader.c.o

**Comment by picca** [comment]
/home/picca/Debian/ufo-filters/ufo-filters/src/readers/ufo-raw-reader.c:136:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread (data, 1, priv->frame_size, priv->fp);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 26%] Building C object src/CMakeFiles/ufofilterread.dir/readers/ufo-tiff-reader.c.o

**Comment by picca** [comment]
/home/picca/Debian/ufo-filters/ufo-filters/src/ufo-denoise-task.c: In function ‘get_max_work_group_size’:
/home/picca/Debian/ufo-filters/ufo-filters/src/ufo-denoise-task.c:165:23: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     *x_worker_count = ULLONG_MAX;
                       ^~~~~~~~~~
[ 34%] Linking C shared library libufofilterdenoise.so

**Comment by picca** [comment]
/home/picca/Debian/ufo-filters/ufo-filters/src/ufo-ordfilt-task.c: In function ‘get_max_alloc_size’:
/home/picca/Debian/ufo-filters/ufo-filters/src/ufo-ordfilt-task.c:56:28: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     priv->max_alloc_size = ULLONG_MAX;
                            ^~~~~~~~~~
[ 44%] Linking C shared library libufofilterordfilt.so

**Comment by matze** [comment]
How's it going now?

**Comment by picca** [comment]
Hello I get this error now that I do not have oclfft.

r -o CMakeFiles/ufofilterifft.dir/ufo-ifft-task.c.o   -c /home/picca/Debian/ufo-filters/ufo-filters/src/ufo-ifft-task.c
/home/picca/Debian/ufo-filters/ufo-filters/src/ufo-ifft-task.c:29:20: fatal error: oclFFT.h: Aucun fichier ou dossier de ce type
 #include "oclFFT.h"
                    ^
compilation terminated.

**Comment by picca** [comment]
CMake Warning (dev) at /usr/share/cmake-3.7/Modules/FindOpenMP.cmake:179 (if):
  if given arguments:
    "TRUE"
  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindOpenMP.cmake:224 (_OPENMP_GET_SPEC_DATE)
  src/CMakeLists.txt:121 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by matze** [comment]
The problem with oclfft should be solved, the one you have with OpenMP is related to your CMake installation and nothing I could do anything about (except for not using OpenMP).

**Comment by picca** [comment]
Now it works :))

I only have this
it seems that some pluggins forgot to link against clfft

dpkg-shlibdeps: avertissement: debian/ufo-filters/usr/lib/i386-linux-gnu/ufo/libufofilterfilter.so contient une référence au symbole clfftCreateDefaultPlan qui ne peut être résolue : il peut s'agir d'un greffon (« plugin »)
dpkg-shlibdeps: avertissement: 9 autres avertissements semblables ont été sautés (utiliser -v pour les voir tous).


I think that once done you can do a 0.11.1 release for inclusion into Debian :))

**Comment by matze** [comment]
Done, sir!

**Comment by picca** [comment]
uploaded :))

Lets see

**Comment by matze** [comment]
Thanks! Is this a public process that I can follow along?

**Comment by picca** [comment]
here it is

https://ftp-master.debian.org/new/ufo-filters_0.11.1+dfsg1-1.html

but you will not see the internal discussion.

I will receive an email fromthe ftp-master with REJECTED or ACCEPTED
I will forwarded it to you :)

Cheers

**Comment by matze** [comment]
Thanks :+1:
