### ISSUE TITLE
How to test tasks

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-filters#137]
Do we already have something for testing except the generic ufo-core tests? Would be good to have some unit tests like in concert. E.g. the stitching task has a lot of "weird" inputs which would be good to test systematically.

**Comment by matze** [comment]
I started [this](https://github.com/ufo-kit/ufo-tests) a while ago. But the main problem is not to write a few lines of test code but to actually make it run somewhere. Travis is not a good solution which means we need to set up continuous integration service (Jenkins?) somewhere (ufosrv2?). Frankly, speaking, I do not have a good answer :-(

**Comment by tfarago** [comment]
I always feared that Travis would eventually limit us. So let's set up something on ufo2 as you said, I also don't have a better idea. We can continue this via e-mail.
