### ISSUE TITLE
ufo-launch crop - the width of the returned image can be one pixel smaller than requested

### ISSUE THREAD

**Issue by milkdrop** [ufo-kit/ufo-filters#142]
Hello 

Hello, a minor bug: as title says the width of the returned image can be one pixel smaller than requested. Example:
ufo-launch read path="Flat/flat_*.tif" ! crop x=0 width=1344 y=100 height=750 ! write filename=flats/flat-%04i.tif
return files with dimensions width=1343 times height. I noticed that this happens a coupe of times.

Sergei.

**Comment by matze** [comment]
If 95538f17e2 did not fix this issue, please re-open it again. Thanks for the report!
