### ISSUE TITLE
ufo-filters FTBFS with glibc 2.25 

### ISSUE THREAD

**Issue by picca** [ufo-kit/ufo-filters#146]
Hello,

I just got a bug report, whcih shows that ufo-filters doesnot compile with glibc 2.25

look at here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882955

It seem sthat you sjould use gnu99 instead of c99 or find a way to avoid the gnu extension.

Cheers

Fred

**Comment by matze** [comment]
Thanks for the report, Fred!
