### ISSUE TITLE
Deprecate prop-refs

### ISSUE THREAD

**Issue by matze** [ufo-kit/ufo-filters#148]
As far as I can tell, there are no users of [this mechanism](http://ufo-core.readthedocs.io/en/latest/using/json.html#property-sets) and it just complicates things in the JSON parser. We need a transition plan but I think it would be a good idea to get rid of them.

**Comment by tfarago** [comment]
I have no clue what it is, so probably yes :wink:

**Comment by matze** [comment]
I added a link to the docs. But since even you don't know what it is, no one will notice ;-)

**Comment by matze** [comment]
Anyway, wrong repository ;-)
