### ISSUE TITLE
Organize and document OpenCL kernels

### ISSUE THREAD

**Issue by matze** [ufo-kit/ufo-filters#150]
For quite a while we have the `opencl` task and now the `opencl-reduce` task as well. This has the benefit that we do not have to write multiple filters which differ only in miniscule detail. However, adoption has been low because 

1. no user would write their own OpenCL kernels, it's not so simple to get anyway
2. the kernels that are available are scattered in multiple files
3. `opencl` loads `default.cl` if none is specified but the kernels in there are not that useful for the average user
4. none of the kernels are documented properly (e.g. purpose, compatibility with the `opencl` task)

With issues https://github.com/ufo-kit/tofu/issues/68 we should embrace these filters though and provide a set of useful reduce and per-pixel operations.

- [x] Add a new document section
- [x] Decide on a set of useful operations and implement them
- [x] Check if the `default.cl` content should be moved
- [x] Consolidate kernel files if necessary

---

### Kernels for opencl

- [x] fix-nan-and-inf
- [x] absorptivity
- [x] NLM noise reduction

### Kernels for opencl-reduce

- [x] minimum
- [x] maximum
- [x] average

**Comment by tfarago** [comment]
On the top of everything, we shouldn't forget reductors which actually reduce the number of dimensions which I started in [reductor.cl](https://github.com/ufo-kit/ufo-filters/blob/master/src/kernels/reductor.cl).

**Comment by matze** [comment]
> On the top of everything, we shouldn't forget reductors which actually reduce the number of dimensions which I started in reductor.cl.

:+1: but this is more related to other plugin developers, right? So that piece of documentation should probably go to the relevant section in the ufo-core manual.

**Comment by tfarago** [comment]
I wanted to touch point 2 "Decide on a set of useful operations and implement them". We should implement the pixel-wise reductors and at the same time reductors which would use the same operations, like average, but in a dimension-reduction fashion. Just to reuse the code as much as possible. Then we can add another task, e.g. `reduction` and make a parameter which would enable people to choose from the operations. So, basically we should implement our operations not as kernels but as functions and then in `opencl-kernel` they would be wrapped into a kernel and in `reduction` they would be wrapped into the kernel which does the dimensional reduction.

**Comment by tfarago** [comment]
I mean it's not completely coupled, I just thought we might wanna get rid of these two birds with one stone because very soon, I will need the reductors for back projection parameter optimization.

**Comment by matze** [comment]
> then we can add another task, e.g. reduction and make a parameter which would enable people to choose from the operations.

This is exactly what `opencl-reduce` does right now … you do not even have to specify a filename in case the functionality is defined in the default kernel file. Now, I would avoid overthinking and -complicating this issue, just let me get started and then we can discuss further.

**Comment by tfarago** [comment]
I know that it does that, but I need moah! :smile: What do I do when I want to reduce the number of dimensions? Basically, I have NxN image and want to get a scalar result. It's basically `numpy.average(image)` (what I am talking about) vs `numy.average(image, axis=0)` (what you are implementing here) (of course the latter code for case of 3D input `image`). I don't see how would the `opencl-reduce` do the dimension reduction now. I don't want to overthink it, just make sure when I need it I don't need to write too much code. So this should be settled _before_ starting to write the code. The question is, do we need two tasks for reduction along z (image stream) and reduction along the other dimensions? From the user perspective I would like to have one task named `reduce` (ha! It exists already...) and a parameter `dimension` specifying the axis along which to reduce (x=lateral, y=vertical, z=the image stream). What do you think?

**Comment by matze** [comment]
I know where you are going but the thing is, I want to avoid packing each and every case in a single filter. Otherwise we will end up with a huge filter, lots of logic and a gazillion parameters for which we need just another frontend to make it bearable again (I am not looking at `general-backproject` here :smile:). I will think about a naming convention that might resolve this issue. But yes, that would mean two filters instead of one.

**Comment by tfarago** [comment]
It's a matter of taste: 1. lots of parameters, 2. lots of filters. I would prefer some compromise between those but that's a discussion for another, rather philosophical issue...

**Comment by ldorofeeva** [comment]
Since I already have separate kernels for absorptivity and fix-nan-and-inf, currently in a file smallfilters.cl, should i create another pull request? Is the filename ok?
Kernels names are "absorptivity" and "fix-nan-and-inf".

I think, I can also write Non-local means denoising, but after Christmas holidays.

**Comment by matze** [comment]
All points of the original issue have been resolved, so I will close this one. If we (ever) come back to the more general reduction task let's open another issue specifically for that.
