### ISSUE TITLE
Usage of opencl filter with different kernels

### ISSUE THREAD

**Issue by milkdrop** [ufo-kit/ufo-filters#152]
Hello, 

it is not really that urgent, but could you also supply a brief description of how opencl filter can be used with various kernels? 

thank you.

**Comment by matze** [comment]
I think I don't really understand what you want. So, there is the [general description](http://ufo-filters.readthedocs.io/en/master/filters.html#generic-opencl) that explains the purpose and parameters and then there is the [description](http://ufo-filters.readthedocs.io/en/master/kernels.html) that lists all default kernels if no filename is specified. Do you mean, a description how to use them with arbitrary kernels?

**Comment by milkdrop** [comment]
Hello, 

yes, this, and most importantly, an example of usage would be very appreciated. Frankly, after reading the existing description I had more questions than before reading it, like f.i. where is the default file with kernels in my filesystem if I install filters using yum and your software repository, how filter orders input data and maps it to parameters of actual computing function, etc. I guess one can simply test all of this in trial and error method, however two examples would be  extremely useful in any case. F.i. a simple one with one of the default kernels which does not even have any parameters. For instance, I receive error if I try to execute
ufo-launch read path="flat.tif" ! opencl kernel='nlm_noise_reduction' ! write filename="test.tif"' !    
Error executing pipeline: opencl: Failed to create kernel `nlm_noise_reduction`: CL_INVALID_KERNEL_NAME

and a more complex one which sets all parameters possible, like the "difference" kernel that you use as an example in read-the-docs - how do you read pairs of images in parallel in order to compute the difference? I'm particularly interested in this one, because it has direct application in K-edge subtraction imaging and it also can be used as a very basic tool to analyze changes in the sample which happen during dynamic imaging.

Many thanks!

**Comment by matze** [comment]
> and a more complex one which sets all parameters possible, like the "difference" kernel that you use as an example in read-the-docs - how do you read pairs of images in parallel in order to compute the difference?

If you mean when using `ufo-launch`, that syntax is explained [here](http://ufo-core.readthedocs.io/en/latest/using/quickstart.html#launching-pipelines-on-the-command-line). Basically, brackets and commas denote "parallel" tasks.

> For instance, I receive error if I try to execute
ufo-launch read path="flat.tif" ! opencl kernel='nlm_noise_reduction' ! write filename="test.tif"' !
Error executing pipeline: opencl: Failed to create kernel nlm_noise_reduction: CL_INVALID_KERNEL_NAME

I suppose that's due to the fact, that I moved the kernel very recently. It might be that the `opencl` task is not up-to-date yet. But anyway, I will try to clarify your issues today. But thanks for your input, by the way!

**Comment by milkdrop** [comment]
Thank you! I also suspected that the package for yum is older than the latest master branch. Well,  meanwhile, I'm off to carefully study documentation for core and filter, seems like I'm missing a lot.

**Comment by matze** [comment]
> Thank you! I also suspected that the package for yum is older than the latest master branch.

Sorry, I didn't notice that the CentOS packages for the new release were not building. I fixed that and an update should bring you up again.

**Comment by milkdrop** [comment]
Hi there, 

I've just played with generic kernels - it is an incredible thing.  I would definitely recommend to add pixel-by-pixel pair-wise image subtraction in the list of default kernel, in the future.

**Comment by matze** [comment]
[Done](https://github.com/ufo-kit/ufo-filters/commit/fdc3b1161396dc1004f374ecc5e07241cbe18546), but I am not sure about the name `diff` yet …
