### ISSUE TITLE
writer: don't rescale gray values when converting to less bits

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-filters#159]
If I want to preserve gray values of some feature in a 3D data set I need to compute clipping values from the complete data set and convert to 8 bit without rescaling the gray values in the writer (I rescale myself by means of the `calculate` filter). This was once possible but now I don't see any options for this. Can we get it back?

**Comment by matze** [comment]
Hmm, I can't remember removing such an obviously important feature. But anyway, I'll bring it back.
