### ISSUE TITLE
How to do convolution

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-filters#161]
I decided to do convolution and my journey was very short. I tried this
`ufo-launch [read path=foo.tif ! fft dimensions=2, read path=bar.tif ! fft dimensions=2] ! opencl filename=complex.cl kernel=c_mul ! ifft dimensions=2 ! write filename=foo.tif`
First I had to modify the horizontal dimension in the `opencl` task in order to satisfy the `c_mul` kernel, this could be fixed easily I think, or not even that much fixed as "unified" with the conventions used in the `opencl` task. But I get segmentation fault when I execute that thing and am not sure where from. Has anyone ever done convolution with UFO already?
The error message:
```bash
(ufo-launch:28218): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'UfoTaskNode'

(ufo-launch:28218): Ufo-CRITICAL **: ufo_task_node_set_partition: assertion 'UFO_IS_TASK_NODE (node)' failed

(ufo-launch:28218): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'UfoNode'

(ufo-launch:28218): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'UfoNode'

(ufo-launch:28218): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'UfoTask'

(ufo-launch:28218): GLib-GObject-CRITICAL **: g_type_interface_peek: assertion 'instance_class != NULL' failed
Segmentation fault (core dumped)
```

**Comment by matze** [comment]
What happens with one GPU device?

**Comment by tfarago** [comment]
It happens with one.

**Comment by matze** [comment]
Let me know if you still have issues.
