### ISSUE TITLE
How to indicate type of input

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-filters#162]
I still want to do the convolution. :smile: I like the `opencl` task but the requisition width is twice the actual width and I don't see an elegant way in the `c_mul` kernel to squeeze the width to the actual one. On the top of that, I am afraid to break some functionality. Is there already some way to determine that the input data type is a complex one? If not, we could add it to the metadata I guess.

**Comment by matze** [comment]
>  On the top of that, I am afraid to break some functionality. Is there already some way to determine that the input data type is a complex one?

Nope, not yet. It's currently implied as you know. We might tag it through metadata although I think it's pretty fundamental and probably requires its own API and sanity checks.

**Comment by matze** [comment]
Alright, so I am on to something but I think I can only finish it by Monday.

**Comment by matze** [comment]
Of course I meant Thursday …

**Comment by matze** [comment]
Alright, this works and also complex multiplication works with the provided kernel (you will probably need to insert a `swap-quadrant` on your convolution kernel though). There is a bit of implicit assumptions right now but at least the infrastructure to add more constraints on a task-level. Not sure though if the scheduler is supposed to enforce that though.

**Comment by tfarago** [comment]
Yep, works well, thanks!
