### ISSUE TITLE
Should reader's start, number, step properties work on images and not files?

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-filters#164]
I cannot really see a use case of these attributes for a multi-page file sequence. E.g. if I now want to reconstruct a data set by using every second projection I am screwed. So, I think it would make much more sense to make these attributes reflect images in a sequence and not files.

**Comment by tfarago** [comment]
@matze what do you think?

**Comment by matze** [comment]
I think we should *not* remove the ability to filter individual files. That would break all existing asumptions. We can of course add the ability to filter within multi-page TIFFs.

**Comment by tfarago** [comment]
OK, I will come up with something.

**Comment by matze** [comment]
Good luck :smile:

**Comment by matze** [comment]
Any news on that?

**Comment by tfarago** [comment]
Thanks for reminding me, I could have a look at this this week.
