### ISSUE TITLE
Turn NLM denoise kernel into a real filter

### ISSUE THREAD

**Issue by matze** [ufo-kit/ufo-filters#170]
@maximweb proposed a smarter NLM filter which does not require figuring out the noise level from outside. This would also make it a lot easier and safer to mess with NLM parameters.

**Comment by maximweb** [comment]
Yes! This would be an awesome enhancement for the ring detection: [ufo-upiv repo](https://github.com/ufo-kit/ufo-upiv)

For testing purposes I used an [ImageJ/Fiji plugin](https://imagej.net/Non_Local_Means_Denoise) which comes with a feature "Auto estimate sigma". The authors reference an implementation by [Immerkaer, J. 1996](https://www.sciencedirect.com/science/article/pii/S1077314296900600)
For the mentioned plugin the code is available and the magic appears to happen in [getGlobalNoiseLevel](https://github.com/thorstenwagner/ij-nl-means/blob/210d63bd7ddce8186f52c8c72c005fbc856fb13b/src/main/java/de/biomedical_imaging/ij/nlMeansPlugin/NLMeansDenoising_.java#L510) function.

As far as I am aware, the OpenCL NLM kernel also accepts some radii as argument. However, I do not know whethere these parameters can or should be optimized automatically.

**Comment by matze** [comment]
Re-open because auto estimation of sigma is not implemented yet.

**Comment by milkdrop** [comment]
Hi, 

could you please roll out these changes already so system build libufofilternonlocalmeans.so? Please DO NOT do auto-estimation of parameters - all these auto-estimation tricks are very situational and won't necessarily work in a general case. Exhaustive explanation of what each of parameters mean can be found, for instance, https://hal.archives-ouvertes.fr/hal-00468856/document (On the parameter choice for the Non-Local Means Vincent Duval et al page 3):
1) The patch size s, which is often set to 7×7 or 9×9, but should a priori be related to the scale of objects in the image. (UFOs PATCH_RADIUS)
2) The smoothing parameter, which stands for the typical distance between similar patches, and which depends on the noise level. Some authors have proposed to choose it proportional to the noise standard deviation. (UFOs SIGMA)
3) The size of the search window W, which has a dramatic impact on the computation time, but which also has an influence on the visual quality of the results. (UFO's SEARCH_RADIUS)

Thank you,
Sergei.

**Comment by tfarago** [comment]
I rewrote the kernel in #182 and will add the automatic sigma estimation soon. It will be optional, so users will still have full control.

**Comment by tfarago** [comment]
So that PR is almost finished. There is also a *fast* option now, which computes the same apart from the Gaussian windowing. You can see the updated filter docs [here](https://ufo-filters.readthedocs.io/en/nlm/filters.html#non-local-means-denoising). If you have remarks please post them here, I will let the PR "mature" a bit and merge it later.

**Comment by tfarago** [comment]
I guess we can close this, if needed, reopen.
