### ISSUE TITLE
ufo-launch and tofu commands output one large .tif

### ISSUE THREAD

**Issue by rmaciver** [ufo-kit/ufo-filters#188]
The output of ufo-launch and tofu is one large TIF file. I expect from previous work with ufo-kit that the results will be written as multiple files.  After splitting into individual files, the output looks ok, the main issue is that a multi-page file is output. I am running ufo-kit in a Docker container built with the master branch of ufo-core and ufo-fiters (10 October). The tiff dependency is libtiff5-dev. 

Even the simplest pipeline will output a multi-page file rather than individual files, for example, reading a path with 10 .tif files:

ufo-launch -t read path=*.tif ! write filename=output/%05i.tif

I do not encounter this issue with docker containers built with the ufo-core and ufo-filters .deb packages: the output is split into multiple .tif files as expected. 

Can anyone suggest what to check to solve this issue? Thanks, R. MacIver

**Comment by tfarago** [comment]
The default behavior of UFO has changed in order not to overwhelm filesystems with many files. If you need the old behavior, please use the `bytes-per-file=0` flag in the writer. If you want single tif files which are not BigTiff, please also use `tiff-bigtiff=False`.
