### ISSUE TITLE
Problems with 8-bit 

### ISSUE THREAD

**Issue by milkdrop** [ufo-kit/ufo-filters#189]
Hello, 

I need help with investigating strange behavior of ufo-launch when working with 8-bit tiffs. If you “crop” 8bit tiffs it would write them by default as 32bits images. If you explicitly add option bits=8 it will mess up the values. The histogram would look like a discrete set of numbers, f.i. values 66, 87, 117 will appear 0 times, which is incorrect. See attached file
![8_bit_cropping_issue](https://user-images.githubusercontent.com/11661545/69352404-83648800-0c42-11ea-9a0d-4df03df6b449.jpg)
What puzzles me is that this does not appear to happen all the time. After the same three operations (PR, tofu tomo with 8 bit flag, and then ufo-launch crop) I can get nice data too
![8_bit_cropping_no_issue](https://user-images.githubusercontent.com/11661545/69352401-83648800-0c42-11ea-8326-05c611f9558f.png)
while yesterday I tried it on the same data and got "dented" histogram. Unfortunately I haven't taken a screenshot and cannot reproduce this error now with the same input data.

Cheers,
Sergei.

**Comment by tfarago** [comment]
Try the option `rescale=False` in the writer. In general there can be "dents" if there are only a few values in the data. E.g. if there are 2 pixels with values [0, 1], they will be rescaled to [0, 255] when `rescale=True`. Hope that helps.

**Comment by milkdrop** [comment]
yep, rescale=False fixes the problem. Many thanks for the prompt reply.
