### ISSUE TITLE
Enable Multidistance Phase retrieval

### ISSUE THREAD

**Issue by MathiasHurst** [ufo-kit/ufo-filters#204]
Can you implement the following phase retrieval filter, for multidistance phaseretrieval? Usually 2-4 distances will be used.

1/ ( SUM_i( 2 * sin(pi * lambda * z_i * k^2) ) + 10^-regularization_rate  )

with frequency k
propagation distance z
wavelength lambda

**Comment by tfarago** [comment]
Are you sure it's not sum [1 / (foo + bar)]? Hence, the sum of multiple CTFs?

**Comment by MathiasHurst** [comment]
Hi Tomas,
are there any news on this?
Bests,
Mathias

**Comment by tfarago** [comment]
Not yet, but thanks for reminding me. Next week I should have some time to check this.

**Comment by MathiasHurst** [comment]
Hi Tomas,
sorry meanwhile I used the python version of this and forgot about the issue. Filter for weakly absorbing sample with a slowly variing phase with homogenous composition is:

CTF = 2 * sin(pi * lambda * z_i * k^2) -  2 * beta/delta * cos(pi * lambda * z_i * k^2)

FFT(PHI)  = SUM_i [ ( FFT(I_i -1) ) * CTF ] / SUM_i [ CTF^2 + epsilon ]

There are some variiations for pure phase or non homogenous objects, but I think this is the approach with the best ratio between applicabilitiy and simplictiy.
If used with real data, Image alignment is really crucial.
