### ISSUE TITLE
make "error" 

### ISSUE THREAD

**Issue by dengtijian** [ufo-kit/ufo-filters#220]
make "error"

In file included from /usr/local/include/glib-2.0/glib/glib-typeof.h:39,
                 from /usr/local/include/glib-2.0/glib/gatomic.h:28,
                 from /usr/local/include/glib-2.0/glib/gthread.h:32,
                 from /usr/local/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/local/include/glib-2.0/glib.h:32,
                 from /usr/local/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/local/include/glib-2.0/glib-object.h:22,
                 from /usr/local/include/ufo-0/ufo/ufo-basic-ops.h:27,
                 from /usr/local/include/ufo-0/ufo/ufo.h:25,
                 from /home/dengtijian/UFO/ufo-filters/deps/oclfft/oclFFT.h:63,
                 from /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_internal.h:52,
                 from /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_execute.cpp:49:
/usr/include/c++/9/type_traits:2753:3: error: template with C linkage
 2753 |   template<typename _Fn, typename... _Args>
      |   ^~~~~~~~
In file included from /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_internal.h:52,
                 from /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_execute.cpp:49:
/home/dengtijian/UFO/ufo-filters/deps/oclfft/oclFFT.h:53:1: note: ‘extern "C"’ linkage started here
   53 | extern "C" {
      | ^~~~~~~~~~
make[2]: *** [deps/oclfft/CMakeFiles/oclfft.dir/build.make:63: deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:385: deps/oclfft/CMakeFiles/oclfft.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
and  cmake showing "No package 'clFFT' found"

-- Checking for module 'clFFT'
--   No package 'clFFT' found

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I want to know if make 'error' is caused by the package 'clFFT'. Or other resons?

**Comment by tfarago** [comment]
Yes, CMake cannot find clFFT and that is strange since that package is bundled together with ufo-filters. Please provide the precise steps how you tried to build this and your OS info and dependency versions, including CMake version. A quick solution could be just to try with meson.

**Comment by matze** [comment]
> Yes, CMake cannot find clFFT and that is strange since that package is bundled together with ufo-filters.

No, not that strange and expected. clFFT is the AMD FFT library, oclfft is the one from Apple we bundle. If clFFT cannot be found (very, very likely on most systems) we fall back to oclfft. So the actual problem seems to be building oclfft. I'd also try building with verbose flags.

**Comment by tfarago** [comment]
Right, sorry, was too quick. Anyway, from another glance it looks like c++ is trying to use some template and doesn't like the "extern C" in the oclfft and I don't know anything about this unfortunately. However, if you run something like `make VERBOSE=1 -d` we will have a ton of debugging output to go through.

**Comment by dengtijian** [comment]
> Yes, CMake cannot find clFFT and that is strange since that package is bundled together with ufo-filters. Please provide the precise steps how you tried to build this and your OS info and dependency versions, including CMake version. A quick solution could be just to try with meson.

**Comment by dengtijian** [comment]
> Yes, CMake cannot find clFFT and that is strange since that package is bundled together with ufo-filters. Please provide the precise steps how you tried to build this and your OS info and dependency versions, including CMake version. A quick solution could be just to try with meson.

sorry for accidentally closing the issue.

build setps:
cd /home/dengtijian/UFO/ufo-filters/build
sudo cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib64

-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so
-- Checking for module 'ufo>=0.16'
--   Found ufo, version 0.16.0
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.1.0")
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found suitable version "1.10.4", minimum required is "1.8")
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "80")
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found OpenCV: /usr/local (found version "4.5.5")
-- Checking for module 'libuca>=1.2'
--   Found libuca, version 2.4.0
-- Checking for module 'libtiff-4>=4.0.0'
--   Found libtiff-4, version 4.1.0
-- Checking for module 'clFFT'
--   No package 'clFFT' found
-- Checking for module 'clblast'
--   Found clblast, version 1.5.2
-- Checking for module 'pangocairo'
--   Found pangocairo, version 1.44.7
-- Checking for module 'opencv'
--   Found opencv, version 4.5.5
-- Checking for module 'libzmq'
--   Found libzmq, version 4.3.2
-- Checking for module 'json-glib-1.0'
--   Found json-glib-1.0, version 1.6.7
-- Found PythonInterp: /usr/bin/python (found version "3.8.10")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dengtijian/UFO/ufo-filters/build

and sudo make, then get above "error"

cmake version 3.16.3

OS info:
Windows 11 Profsssional Edition (21H2) and WSL2 with Ubuntu 20.04 LTS
NVIDIA Quadro P520, driver version: 512.15, CUDA Version: 11.6

**Comment by tfarago** [comment]
You pasted the output of cmake, now please change the `sudo make` to `sudo make VERBOSE=1 -d` and provide the relevant parts (by relevant I mean the output lines leading to the error in oclfft). Don't forget to do `sudo make clean` before, otherwise nothing will be built.

**Comment by tfarago** [comment]
Just FYI, CUDA doesn't work on WSL2 yet. You can get it working on your CPU's integrated graphic card, I recently tried it with Intel.

**Comment by tfarago** [comment]
https://ufo-core.readthedocs.io/en/latest/install/windows.html

**Comment by dengtijian** [comment]
> You pasted the output of cmake, now please change the `sudo make` to `sudo make VERBOSE=1 -d` and provide the relevant parts (by relevant I mean the output lines leading to the error in oclfft). Don't forget to do `sudo make clean` before, otherwise nothing will be built.

    49  #ifndef __CLFFT_H
    50  #define __CLFFT_H
    51
    52  #ifdef __cplusplus
    53  extern "C" {
    54  #endif
    55
    56  #define CL_TARGET_OPENCL_VERSION 120
    57  #ifdef __APPLE__
    58  #include <OpenCL/cl.h>
    59  #else
    60  #include <CL/cl.h>
    61  #endif
    62  #include <stdio.h>
    63  #include <ufo/ufo.h>

**Comment by tfarago** [comment]
You pasted the relevant _source code parts_ of the file `deps/oclfft/oclFFT.h`. Now please paste the relevant _output parts_ of `sudo make VERBOSE=1 -d`. On my system, it looks like this:

```bash
    Must remake target 'deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o'.
make[2]: Entering directory '/home/tomas/dev/tmp/ufo-filters/build'
Putting child 0x5578ffc56d20 (deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o) PID 14326 on the chain.
Live child 0x5578ffc56d20 (deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o) PID 14326 
[  1%] Building CXX object deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o
Reaping winning child 0x5578ffc56d20 PID 14326 
cd /home/tomas/dev/tmp/ufo-filters/build/deps/oclfft && /usr/bin/c++  -DG_LOG_DOMAIN=\"Ufo\" -Doclfft_EXPORTS -I/home/tomas/dev/tmp/ufo-filters/deps/oclfft -I/home/tomas/.local/share/cenv/ufo/include/ufo-0 -I/usr/include/python3.8 -I/usr/include/json-glib-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -fPIC   -Wall -Wextra -fPIC -Wno-unused-parameter -o CMakeFiles/oclfft.dir/fft_execute.cpp.o -c /home/tomas/dev/tmp/ufo-filters/deps/oclfft/fft_execute.cpp
Live child 0x5578ffc56d20 (deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o) PID 14328 
Reaping winning child 0x5578ffc56d20 PID 14328 
Removing child 0x5578ffc56d20 PID 14328 from chain.
    Successfully remade target file 'deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o'.

```

**Comment by dengtijian** [comment]
> You pasted the relevant _source code parts_ of the file `deps/oclfft/oclFFT.h`. Now please paste the relevant _output parts_ of `sudo make VERBOSE=1 -d`. On my system, it looks like this:
> 
> ```shell
>     Must remake target 'deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o'.
> make[2]: Entering directory '/home/tomas/dev/tmp/ufo-filters/build'
> Putting child 0x5578ffc56d20 (deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o) PID 14326 on the chain.
> Live child 0x5578ffc56d20 (deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o) PID 14326 
> [  1%] Building CXX object deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o
> Reaping winning child 0x5578ffc56d20 PID 14326 
> cd /home/tomas/dev/tmp/ufo-filters/build/deps/oclfft && /usr/bin/c++  -DG_LOG_DOMAIN=\"Ufo\" -Doclfft_EXPORTS -I/home/tomas/dev/tmp/ufo-filters/deps/oclfft -I/home/tomas/.local/share/cenv/ufo/include/ufo-0 -I/usr/include/python3.8 -I/usr/include/json-glib-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -fPIC   -Wall -Wextra -fPIC -Wno-unused-parameter -o CMakeFiles/oclfft.dir/fft_execute.cpp.o -c /home/tomas/dev/tmp/ufo-filters/deps/oclfft/fft_execute.cpp
> Live child 0x5578ffc56d20 (deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o) PID 14328 
> Reaping winning child 0x5578ffc56d20 PID 14328 
> Removing child 0x5578ffc56d20 PID 14328 from chain.
>     Successfully remade target file 'deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o'.
> ```

 Must remake target 'deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o'.
make[2]: Entering directory '/home/dengtijian/UFO/ufo-filters/build'
Putting child 0x557e51ec64d0 (deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o) PID 6321 on the chain.
Live child 0x557e51ec64d0 (deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o) PID 6321
[  0%] Building CXX object deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o
Reaping winning child 0x557e51ec64d0 PID 6321
cd /home/dengtijian/UFO/ufo-filters/build/deps/oclfft && /usr/bin/c++  -DG_LOG_DOMAIN=\"Ufo\" -Doclfft_EXPORTS -I/home/dengtijian/UFO/ufo-filters/deps/oclfft -I/usr/local/include/ufo-0 -I/usr/local/include/json-glib-1.0 -I/usr/local/include/glib-2.0 -I/usr/local/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/python3.8 -I/usr/include/libmount -I/usr/include/blkid  -fPIC   -Wall -Wextra -fPIC -Wno-unused-parameter -o CMakeFiles/oclfft.dir/fft_execute.cpp.o -c /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_execute.cpp
Live child 0x557e51ec64d0 (deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o) PID 6322
...
...
...
Reaping losing child 0x557e51ec64d0 PID 6322
make[2]: *** [deps/oclfft/CMakeFiles/oclfft.dir/build.make:63: deps/oclfft/CMakeFiles/oclfft.dir/fft_execute.cpp.o] Error 1
Removing child 0x557e51ec64d0 PID 6322 from chain.
make[2]: Leaving directory '/home/dengtijian/UFO/ufo-filters/build'
Reaping losing child 0x55702ddace70 PID 6320
make[1]: *** [CMakeFiles/Makefile2:385: deps/oclfft/CMakeFiles/oclfft.dir/all] Error 2
Removing child 0x55702ddace70 PID 6320 from chain.
make[1]: Leaving directory '/home/dengtijian/UFO/ufo-filters/build'
Reaping losing child 0x5572d460f260 PID 6317
make: *** [Makefile:141: all] Error 2
Removing child 0x5572d460f260 PID 6317 from chain.

**Comment by tfarago** [comment]
Please run this and paste the output:
```bash
cd /home/dengtijian/UFO/ufo-filters/build/deps/oclfft && /usr/bin/c++ -v -DG_LOG_DOMAIN="Ufo" -Doclfft_EXPORTS -I/home/dengtijian/UFO/ufo-filters/deps/oclfft -I/usr/local/include/ufo-0 -I/usr/local/include/json-glib-1.0 -I/usr/local/include/glib-2.0 -I/usr/local/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/python3.8 -I/usr/include/libmount -I/usr/include/blkid -fPIC -Wall -Wextra -fPIC -Wno-unused-parameter -o CMakeFiles/oclfft.dir/fft_execute.cpp.o -c /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_execute.cpp
```

**Comment by dengtijian** [comment]
> 

Using built-in specs.
COLLECT_GCC=/usr/bin/c++
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
COLLECT_GCC_OPTIONS='-v' '-D' 'G_LOG_DOMAIN=Ufo' '-D' 'oclfft_EXPORTS' '-I' '/home/dengtijian/UFO/ufo-filters/deps/oclfft' '-I' '/usr/local/include/ufo-0' '-I' '/usr/local/include/json-glib-1.0' '-I' '/usr/local/include/glib-2.0' '-I' '/usr/local/lib/x86_64-linux-gnu/glib-2.0/include' '-I' '/usr/include/python3.8' '-I' '/usr/include/libmount' '-I' '/usr/include/blkid' '-Wall' '-Wextra' '-fPIC' '-Wno-unused-parameter' '-o' 'CMakeFiles/oclfft.dir/fft_execute.cpp.o' '-c' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/9/cc1plus -quiet -v -I /home/dengtijian/UFO/ufo-filters/deps/oclfft -I /usr/local/include/ufo-0 -I /usr/local/include/json-glib-1.0 -I /usr/local/include/glib-2.0 -I /usr/local/lib/x86_64-linux-gnu/glib-2.0/include -I /usr/include/python3.8 -I /usr/include/libmount -I /usr/include/blkid -imultiarch x86_64-linux-gnu -D_GNU_SOURCE -D G_LOG_DOMAIN=Ufo -D oclfft_EXPORTS /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_execute.cpp -quiet -dumpbase fft_execute.cpp -mtune=generic -march=x86-64 -auxbase-strip CMakeFiles/oclfft.dir/fft_execute.cpp.o -Wall -Wextra -Wno-unused-parameter -version -fPIC -fasynchronous-unwind-tables -fstack-protector-strong -Wformat-security -fstack-clash-protection -fcf-protection -o /tmp/ccON3QNp.s
GNU C++14 (Ubuntu 9.4.0-1ubuntu1~20.04.1) version 9.4.0 (x86_64-linux-gnu)
        compiled by GNU C version 9.4.0, GMP version 6.2.0, MPFR version 4.0.2, MPC version 1.1.0, isl version isl-0.22.1-GMP

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/9"
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/9/../../../../x86_64-linux-gnu/include"
ignoring duplicate directory "."
ignoring duplicate directory "."
ignoring duplicate directory "/usr/local/hdf5/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/dengtijian/UFO/ufo-filters/deps/oclfft
 /usr/local/include/ufo-0
 /usr/local/include/json-glib-1.0
 /usr/local/include/glib-2.0
 /usr/local/lib/x86_64-linux-gnu/glib-2.0/include
 /usr/include/python3.8
 /usr/include/libmount
 /usr/include/blkid
 .
 /usr/local/hdf5/include
 /usr/include/c++/9
 /usr/include/x86_64-linux-gnu/c++/9
 /usr/include/c++/9/backward
 /usr/lib/gcc/x86_64-linux-gnu/9/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
GNU C++14 (Ubuntu 9.4.0-1ubuntu1~20.04.1) version 9.4.0 (x86_64-linux-gnu)
        compiled by GNU C version 9.4.0, GMP version 6.2.0, MPFR version 4.0.2, MPC version 1.1.0, isl version isl-0.22.1-GMP

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: 65fe925b83d3956b533de4aaba7dace0
In file included from /usr/local/include/glib-2.0/glib/glib-typeof.h:39,
                 from /usr/local/include/glib-2.0/glib/gatomic.h:28,
                 from /usr/local/include/glib-2.0/glib/gthread.h:32,
                 from /usr/local/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/local/include/glib-2.0/glib.h:32,
                 from /usr/local/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/local/include/glib-2.0/glib-object.h:22,
                 from /usr/local/include/ufo-0/ufo/ufo-basic-ops.h:27,
                 from /usr/local/include/ufo-0/ufo/ufo.h:25,
                 from /home/dengtijian/UFO/ufo-filters/deps/oclfft/oclFFT.h:63,
                 from /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_internal.h:52,
                 from /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_execute.cpp:49:
/usr/include/c++/9/type_traits:56:3: error: template with C linkage
   56 |   template<typename _Tp, _Tp __v>
      |   ^~~~~~~~
In file included from /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_internal.h:52,
                 from /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_execute.cpp:49:
/home/dengtijian/UFO/ufo-filters/deps/oclfft/oclFFT.h:53:1: note: ‘extern "C"’ linkage started here
   53 | extern "C" {
      | ^~~~~~~~~~
...
...
...
/usr/local/include/glib-2.0/gobject/gobject.h: In function ‘void g_assert_finalize_object(GObject*)’:
<command-line>: error: ‘Ufo’ was not declared in this scope
/usr/local/include/glib-2.0/glib/gtestutils.h:185:69: note: in expansion of macro ‘G_LOG_DOMAIN’
  185 |                                                g_assertion_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, \
      |                                                                     ^~~~~~~~~~~~
/usr/local/include/glib-2.0/gobject/gobject.h:812:3: note: in expansion of macro ‘g_assert_true’
  812 |   g_assert_true (G_IS_OBJECT (weak_pointer));
      |   ^~~~~~~~~~~~~
<command-line>: error: ‘Ufo’ was not declared in this scope
/usr/local/include/glib-2.0/glib/gtestutils.h:197:69: note: in expansion of macro ‘G_LOG_DOMAIN’
  197 |                                                g_assertion_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, \
      |                                                                     ^~~~~~~~~~~~
/usr/local/include/glib-2.0/gobject/gobject.h:815:3: note: in expansion of macro ‘g_assert_null’
  815 |   g_assert_null (weak_pointer);
      |   ^~~~~~~~~~~~~

**Comment by tfarago** [comment]
And now please run this:
```bash
cd /home/dengtijian/UFO/ufo-filters/build/deps/oclfft && /usr/bin/c++ -v -DG_LOG_DOMAIN=\"Ufo\" -Doclfft_EXPORTS -I/home/dengtijian/UFO/ufo-filters/deps/oclfft -I/usr/local/include/ufo-0 -I/usr/local/include/json-glib-1.0 -I/usr/local/include/glib-2.0 -I/usr/local/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/python3.8 -I/usr/include/libmount -I/usr/include/blkid -fPIC -Wall -Wextra -fPIC -Wno-unused-parameter -o CMakeFiles/oclfft.dir/fft_execute.cpp.o -c /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_execute.cpp
```

**Comment by tfarago** [comment]
I.e., make sure you have the backslashes in place here: `-DG_LOG_DOMAIN=\"Ufo\"`

**Comment by dengtijian** [comment]
> And now please run this:
> 
> ```shell
> cd /home/dengtijian/UFO/ufo-filters/build/deps/oclfft && /usr/bin/c++ -v -DG_LOG_DOMAIN=\"Ufo\" -Doclfft_EXPORTS -I/home/dengtijian/UFO/ufo-filters/deps/oclfft -I/usr/local/include/ufo-0 -I/usr/local/include/json-glib-1.0 -I/usr/local/include/glib-2.0 -I/usr/local/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/python3.8 -I/usr/include/libmount -I/usr/include/blkid -fPIC -Wall -Wextra -fPIC -Wno-unused-parameter -o CMakeFiles/oclfft.dir/fft_execute.cpp.o -c /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_execute.cpp
> ```

full screen loops as shown below:
............................................................................................................................................................................................................................................

In file included from /usr/local/include/glib-2.0/glib/glib-typeof.h:39,
                 from /usr/local/include/glib-2.0/glib/gatomic.h:28,
                 from /usr/local/include/glib-2.0/glib/gthread.h:32,
                 from /usr/local/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/local/include/glib-2.0/glib.h:32,
                 from /usr/local/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/local/include/glib-2.0/glib-object.h:22,
                 from /usr/local/include/ufo-0/ufo/ufo-basic-ops.h:27,
                 from /usr/local/include/ufo-0/ufo/ufo.h:25,
                 from /home/dengtijian/UFO/ufo-filters/deps/oclfft/oclFFT.h:63,
                 from /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_internal.h:52,
                 from /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_execute.cpp:49:
/usr/include/c++/9/type_traits:2753:3: error: template with C linkage
 2753 |   template<typename _Fn, typename... _Args>
      |   ^~~~~~~~
In file included from /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_internal.h:52,
                 from /home/dengtijian/UFO/ufo-filters/deps/oclfft/fft_execute.cpp:49:
/home/dengtijian/UFO/ufo-filters/deps/oclfft/oclFFT.h:53:1: note: ‘extern "C"’ linkage started here
   53 | extern "C" {
      | ^~~~~~~~~~

**Comment by tfarago** [comment]
And what is the output of `/usr/bin/c++ --version` please?

**Comment by tfarago** [comment]
Also what is your glib version?

**Comment by dengtijian** [comment]
> And what is the output of `/usr/bin/c++ --version` please?

/usr/bin/c++ --version

c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by dengtijian** [comment]
> Also what is your glib version?

2.72.1

**Comment by dengtijian** [comment]
> > Also what is your glib version?
> 
> 2.72.1

sorry, 2.73.0

**Comment by tfarago** [comment]
Your version is newer than mine so I can't see the problem you do. I will check this tomorrow.

**Comment by tfarago** [comment]
I just tried with 2.73. Please pull master and try again, if it still doesn't work re-open this.

**Comment by dengtijian** [comment]
> I just tried with 2.73. Please pull master and try again, if it still doesn't work re-open this, otherwise happy UFOing.

cmake, make and make install all work, thanks for your patience!

**Comment by sgasilov** [comment]
#define GLIB_VERSION_MIN_REQUIRED GLIB_VERSION_2_38 - does it mean that we will have to rebuild this library manually on CentOS7or delete this line in CMAKE to compile ufo-filter with older versions of glib? In RHEL 7.x, the libc RPM package is 2.17-324.el7_9. I'm asking because we were going to upgrade all our production servers and wonder if our ANSIBLE script will still work.

**Comment by tfarago** [comment]
In [ufo-core](https://github.com/ufo-kit/ufo-core/commit/6aaa7d28119fcf0fd8c32851e4dfa5269d08feca) this has been done in 2018 already. Are you sure that's the version you have?

**Comment by matze** [comment]
> In RHEL 7.x, the libc RPM package is 2.17-324.el7_9.

Please note glibc and glib are two different things. glibc is the GNU libc C standard library, glib is the utility and foundational library of the GNOME project.
