### ISSUE TITLE
memory-in task ignores number of frames if the buffer location is set to opencl buffer

### ISSUE THREAD

**Issue by jonakopmann** [ufo-kit/ufo-filters#234]
If you use the OpenCl buffer for the memory-in task and have multiple frames it will only copy the first frame and throw an error when the buffer provided is the correct size, this should be fixed, when [this](https://github.com/ufo-kit/ufo-filters/blob/master/src/ufo-memory-in-task.c#L209) checks for the size * number and the [copy](https://github.com/ufo-kit/ufo-filters/blob/master/src/ufo-memory-in-task.c#L214) has the offset added, like the memcpy does.

**Comment by tfarago** [comment]
Can you check out #235 ?

**Comment by jonakopmann** [comment]
yeah this works now
