### ISSUE TITLE
Multi-paged tif reading doesn't work

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-filters#63]
Only the first image in every multi-paged tif file is read.

**Comment by matze** [comment]
I don't think this was ever implemented, so I'll change the issue type to enhancement.

**Comment by tfarago** [comment]
It was 2ca2dafd5b30a11088f528728ff9a87445ec26bf

**Comment by matze** [comment]
Ah damn. But do we really need it though? With all this HDF5 talk going on, I really don't want to touch the reader which is (and probably always will be) an entangled mess of implicit state.

**Comment by tfarago** [comment]
Unfortunately the people who use regular camera software usually have to work with it. On the other hand, I have a python script which splits multitiff files, so we could add that to `tofu`. On the third hand, it means people cannot process their data in "one shot", they first have to split and then they can use whatever UFO pipeline they want, which is kind of not cool.

**Comment by matze** [comment]
But you know how it is now. The reader reads EDF and TIFF, can be parameterized with start, stop, step, offset, this and that, and this will blow up even more with multi-TIFFs (just thinking of a directory full of multi-TIFF gives me headaches).

**Comment by tfarago** [comment]
Yeah, I know, it's ugly enough as it is already... Let's have a good weekend rest and come back to this.

**Comment by matze** [comment]
Is fixed in #64.
