### ISSUE TITLE
2D FFT doesn't work

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-filters#65]
With
```bash
ufo-launch read path="fc/*" end=1 ! fft dimensions=2 ! ifft dimensions=2 ! write filename=foo-%04i.tif
```
my foo file is just NaNs.
@rshkarin I guess this is why the phase retrieveal doesn't work either.

**Comment by matze** [comment]
I cannot reproduce this. Both this command line as well as [this test](https://github.com/ufo-kit/ufo-core/blob/d8781ab637e21f7d239110d80a231c908fb5de46/python/tests/test_plugins.py#L146-L156) give me correct results.

**Comment by tfarago** [comment]
I don't get this. It works for all images but one which was produced by the framework itself. I am sending it to you via email.

**Comment by tfarago** [comment]
One second, I might be on to something.

**Comment by tfarago** [comment]
Nope :disappointed:, sending the image now.

**Comment by matze** [comment]
Do you use the the reader/writer from the wip-branch?

**Comment by tfarago** [comment]
Nope. But I think I know what the problem is, there are `nan`s in the image... So there is nothing wrong actually, sorry.
