### ISSUE TITLE
Encode filetype metadata into filename?

### ISSUE THREAD

**Issue by matze** [ufo-kit/ufo-filters#71]
While using HDF5 now for a while I noticed, we'd have to write a lot of specialty code in order to specify the dataset name. This is cumbersome, so I thought we could encode the dataset name into the filename property itself, i.e. instead of

     ufo-launch foo ! write filename=/tmp/foo.h5 dataset=/bar/baz

we could write the dataset name directly into the filename after a separator

    ufo-launch foo ! write filename=/tmp/foo.h5:/bar/baz

That way we could avoid adding special code in GUIs and the like.

**Comment by tfarago** [comment]
:+1:
