### ISSUE TITLE
Cannot set axis on DFI filter

### ISSUE THREAD

**Issue by matze** [ufo-kit/ufo-filters#75]
@rshkarin: is this intentional?

**Comment by rshkarin** [comment]
@matze these changes are not really important, just leave it as is for a while.

**Comment by matze** [comment]
I don't understand that statement. I am saying I cannot set the axis which makes this method impossible to use with any real data.

**Comment by rshkarin** [comment]
@matze  whoops, I misunderstood the question, as the DFI method consists of several consequently connected filters (zeropadding -> fft1d -> dfi -> swap_quads -> ifft2d -> swap_quads), the rotation axis you need to set in ufo-zeropad-task.c.

**Comment by matze** [comment]
Thanks for the hint! I'll update all our scripts.
