### ISSUE TITLE
ifft 

### ISSUE THREAD

**Issue by chuan137** [ufo-kit/ufo-filters#84]
usually, I would expect a factor like 1/volume in the formula of Fourier Transform.
```
    scale = 1.0f / ((gfloat) requisition->dims[0]);  
    if (priv->fft_dimensions == FFT_2D) { 
        scale /= (gfloat) requisition->dims[0];
    }  
```
it might be `scale /= (gfloat) requisition->dims[1];` ?

**Comment by matze** [comment]
Yes, that's indeed correct.
