### ISSUE TITLE
Do not force CPU in slice filter 

### ISSUE THREAD

**Issue by chuan137** [ufo-kit/ufo-filters#91]
currently slice filter force data copied back to host memory with CPU, which could be a performance breaker. Improve the slice filter, keep data where it is if already on GPU.

**Comment by chuan137** [comment]
@matze could you check my implementation, chuan137@f761431fae9fcd72b9f05c7a93c4729c37a24d92, the performance only improved by a small margin, ~ 15%

**Comment by chuan137** [comment]
fixed. performance is now much better. chuan137@b22aeff4bf61085f1fd3d8b3e8708baac3910f2b

@matze would you check the logic, if we should add more generic scenario?

**Comment by matze** [comment]
In general,  the logic is fine. However, besides the mentioned minor problems, I fear that this could fail at run-time with large data. For example, my GTX Titan Black can allocate at most 1.5 GB out of 6. So at least with tomography we have to do the slicing in main memory. So, my suggestion is to add a property (maybe a boolean `use-gpu`) that allows to make GPU-based slicing opt-in.
