### ISSUE TITLE
Help improvements

### ISSUE THREAD

**Issue by buldo** [ufo-kit/ufo-filters#96]
I think that this is good idea to provide some exapmles of filter chains in help or wiki. 
For ex. FBP, DFI and others.

**Comment by matze** [comment]
Hey, I don't know if Andrei has sent you already a mail but the premier place for reconstruction-related setups is the [https://github.com/ufo-kit/tofu](tofu) project.

Another question is also in which format should these sample chains be written. Pure C? As JSON? In one of the supported third-party languages?
