### ISSUE TITLE
DFI Kernel: lack of variables

### ISSUE THREAD

**Issue by ashkarin** [ufo-kit/ufo-filters#97]
Hi @GGoek ,

I tried to use DFI, but it seems that a part of code is missed.
Please:
1. Change raster_size2, raster_size_2  to raster_size_half
2. Add the part with declaration and calculation of out_idx_mirror, y_offset

**Comment by GGoek** [comment]
Hi,
Unfortunately I committed the wrong version, thank you for noticing! I have changed it and made a pull request, hope it works now.

**Comment by matze** [comment]
#99 should've fixed this.

@ashkarin: please re-open if this is still an issue.
